from pages.base_page import BasePage
from locators.aw_locators import AwLocators
from playwright.sync_api import expect
import pytest
import allure


class HomePage(BasePage):

    def asset_continue_development_feature(self):
        self.is_visible(AwLocators.AW_HOME_PAGE_CONTINUE_DEVELOPMENT_BTN)
        self.click(AwLocators.AW_HOME_PAGE_CONTINUE_DEVELOPMENT_BTN)
        self.is_visible(AwLocators.AW_HOME_PAGE_CONTINUE_DEVELOPMENT_FETCH_ASSET_TASK_HEADER)
        #Enter the first name, last name and the email address
        self.fill(AwLocators.AW_CONTINUE_DEVELOPMENT_FIRST_NAME_INPUT, "Test")
        self.fill(AwLocators.AW_CONTINUE_DEVELOPMENT_LAST_NAME_INPUT, "User")
        self.fill(AwLocators.AW_CONTINUE_DEVELOPMENT_EMAIL_INPUT, "testuser@getnada.com")
        self.click(AwLocators.AW_CONTINUE_DEVELOPMENT_CREATE_REQ_BTN)

    def asset_review_and_approve_feature(self):
        self.is_visible(AwLocators.AW_HOME_PAGE_REVIEW_AND_APPROVE_BTN)
        self.click(AwLocators.AW_HOME_PAGE_REVIEW_AND_APPROVE_BTN)
        self.is_visible(AwLocators.AW_HOME_PAGE_REVIEW_AND_APPROVE_EXCEPTION_MSG)
        expect(self.page.locator(AwLocators.AW_HOME_PAGE_REVIEW_AND_APPROVE_EXCEPTION_MSG)).to_contain_text("Exception in remote application")
        screenshot = self.page.screenshot()
        allure.attach(screenshot, name="Review_and_Approve_Exception", attachment_type=allure.attachment_type.PNG)

    def integration_list_feature(self):
        self.is_visible(AwLocators.AW_HOME_PAGE_INTEGRATION_BTN)
        self.click(AwLocators.AW_HOME_PAGE_INTEGRATION_BTN)
        self.is_visible(AwLocators.AW_INTEGRATION_FEATURE_DESCRIPTION)
        #Select by asset ID
        self.is_visible(AwLocators.AW_INTEGRATION_SEARCH_ASSET_ID_INPUT)
        self.click(AwLocators.AW_INTEGRATION_SEARCH_ASSET_ID_INPUT)
        self.fill(AwLocators.AW_INTEGRATION_SEARCH_ASSET_ID_INPUT, "1027")
        self.is_visible(AwLocators.AW_INTEGRATION_NO_RESULTS_MSG)
        screenshot = self.page.screenshot()
        allure.attach(screenshot, name="Integration_Asset_ID_No_Results", attachment_type=allure.attachment_type.PNG)
        self.is_visible(AwLocators.AW_INTEGRATION_PULL_TAB)
        self.click(AwLocators.AW_INTEGRATION_PULL_TAB)
        self.is_visible(AwLocators.AW_INTEGRATION_NO_RESULTS_MSG)
        screenshot = self.page.screenshot()
        allure.attach(screenshot, name="Integration_Asset_ID_No_Results_1", attachment_type=allure.attachment_type.PNG)
        self.is_visible(AwLocators.AW_INTEGRATION_MANUAL_TAB)
        self.click(AwLocators.AW_INTEGRATION_MANUAL_TAB)
        self.is_visible(AwLocators.AW_TABLE_ROW_ASSET_ID)
        expect(self.page.locator(AwLocators.AW_TABLE_ROW_ASSET_ID)).to_contain_text("1027")
        self.is_visible(AwLocators.AW_TABLE_ROW_REGULATION)
        expect(self.page.locator(AwLocators.AW_TABLE_ROW_REGULATION)).to_contain_text("OR-CPA")
        self.is_visible(AwLocators.AW_TABLE_ROW_RIGHT)
        expect(self.page.locator(AwLocators.AW_TABLE_ROW_RIGHT)).to_contain_text("Access")
        self.is_visible(AwLocators.AW_TABLE_ROW_BRAND)
        expect(self.page.locator(AwLocators.AW_TABLE_ROW_BRAND)).to_contain_text("Demo")
        screenshot = self.page.screenshot()
        allure.attach(screenshot, name="Integration_Asset_ID_Manual_Assets", attachment_type=allure.attachment_type.PNG)
        self.is_visible(AwLocators.AW_INTEGRATION_KAFKA_TAB)
        self.click(AwLocators.AW_INTEGRATION_KAFKA_TAB)
        self.is_visible(AwLocators.AW_INTEGRATION_ASSET_ID_OPTION)
        self.click(AwLocators.AW_INTEGRATION_ASSET_ID_OPTION)
        self.is_visible(AwLocators.AW_INTEGRATION_REGULATION_OPTION)
        self.click(AwLocators.AW_INTEGRATION_REGULATION_OPTION)
        self.is_visible(AwLocators.AW_INTEGRATION_SEARCH_REGULATION_INPUT)
        self.fill(AwLocators.AW_INTEGRATION_SEARCH_REGULATION_INPUT, "")
        self.fill(AwLocators.AW_INTEGRATION_SEARCH_REGULATION_INPUT, "OR-CPA")
        self.is_visible(AwLocators.AW_INTEGRATION_NO_RESULTS_MSG)
        screenshot = self.page.screenshot()
        allure.attach(screenshot, name="Integration_Regulation_No_Results", attachment_type=allure.attachment_type.PNG)
        self.is_visible(AwLocators.AW_INTEGRATION_PULL_TAB)
        self.click(AwLocators.AW_INTEGRATION_PULL_TAB)
        self.is_visible(AwLocators.AW_INTEGRATION_NO_RESULTS_MSG)
        screenshot = self.page.screenshot()
        allure.attach(screenshot, name="Integration_Regulation_No_Results_1", attachment_type=allure.attachment_type.PNG)
        self.is_visible(AwLocators.AW_INTEGRATION_MANUAL_TAB)
        self.click(AwLocators.AW_INTEGRATION_MANUAL_TAB)
        self.is_visible(AwLocators.AW_TABLE_ROW_ASSET_ID)
        expect(self.page.locator(AwLocators.AW_TABLE_ROW_ASSET_ID)).to_contain_text("1027")
        self.is_visible(AwLocators.AW_TABLE_ROW_REGULATION)
        expect(self.page.locator(AwLocators.AW_TABLE_ROW_REGULATION)).to_contain_text("OR-CPA")
        self.is_visible(AwLocators.AW_TABLE_ROW_RIGHT)
        expect(self.page.locator(AwLocators.AW_TABLE_ROW_RIGHT)).to_contain_text("Access")
        self.is_visible(AwLocators.AW_TABLE_ROW_BRAND)
        expect(self.page.locator(AwLocators.AW_TABLE_ROW_BRAND)).to_contain_text("Demo")
        screenshot = self.page.screenshot()
        allure.attach(screenshot, name="Integration_Regulation_Manual_Assets", attachment_type=allure.attachment_type.PNG)
        self.is_visible(AwLocators.AW_INTEGRATION_KAFKA_TAB)
        self.click(AwLocators.AW_INTEGRATION_KAFKA_TAB)
        self.is_visible(AwLocators.AW_INTEGRATION_REGULATION_OPTION)
        self.click(AwLocators.AW_INTEGRATION_REGULATION_OPTION)
        self.is_visible(AwLocators.AW_INTEGRATION_BRAND_OPTION)
        self.click(AwLocators.AW_INTEGRATION_BRAND_OPTION)
        self.is_visible(AwLocators.AW_INTEGRATION_SEARCH_BRAND_INPUT)
        self.fill(AwLocators.AW_INTEGRATION_SEARCH_BRAND_INPUT, "")
        self.fill(AwLocators.AW_INTEGRATION_SEARCH_BRAND_INPUT, "Demo")
        self.is_visible(AwLocators.AW_INTEGRATION_NO_RESULTS_MSG)
        screenshot = self.page.screenshot()
        allure.attach(screenshot, name="Integration_Brand_No_Results", attachment_type=allure.attachment_type.PNG)
        self.is_visible(AwLocators.AW_INTEGRATION_PULL_TAB)
        self.click(AwLocators.AW_INTEGRATION_PULL_TAB)
        self.is_visible(AwLocators.AW_INTEGRATION_NO_RESULTS_MSG)
        screenshot = self.page.screenshot()
        allure.attach(screenshot, name="Integration_Brand_No_Results_1", attachment_type=allure.attachment_type.PNG)
        self.is_visible(AwLocators.AW_INTEGRATION_MANUAL_TAB)
        self.click(AwLocators.AW_INTEGRATION_MANUAL_TAB)
        self.is_visible(AwLocators.AW_TABLE_ROW_ASSET_ID)
        expect(self.page.locator(AwLocators.AW_TABLE_ROW_ASSET_ID)).to_contain_text("1027")
        self.is_visible(AwLocators.AW_TABLE_ROW_REGULATION)
        expect(self.page.locator(AwLocators.AW_TABLE_ROW_REGULATION)).to_contain_text("OR-CPA")
        self.is_visible(AwLocators.AW_TABLE_ROW_RIGHT)
        expect(self.page.locator(AwLocators.AW_TABLE_ROW_RIGHT)).to_contain_text("Access")
        self.is_visible(AwLocators.AW_TABLE_ROW_BRAND)
        expect(self.page.locator(AwLocators.AW_TABLE_ROW_BRAND)).to_contain_text("Demo")
        screenshot = self.page.screenshot()
        allure.attach(screenshot, name="Integration_Brand_Manual_Assets", attachment_type=allure.attachment_type.PNG)

    def development_list_feature(self):
        self.is_visible(AwLocators.AW_HOME_PAGE_DEVELOPMENT_BTN)
        self.click(AwLocators.AW_HOME_PAGE_DEVELOPMENT_BTN)
        self.is_visible(AwLocators.AW_INTEGRATION_FEATURE_DESCRIPTION)
        #Select by asset ID
        self.is_visible(AwLocators.AW_INTEGRATION_SEARCH_ASSET_ID_INPUT)
        self.click(AwLocators.AW_INTEGRATION_SEARCH_ASSET_ID_INPUT)
        self.fill(AwLocators.AW_INTEGRATION_SEARCH_ASSET_ID_INPUT, "1027")
        expect(self.page.locator(AwLocators.AW_TABLE_ROW_ASSET_ID)).to_contain_text("1027")
        self.is_visible(AwLocators.AW_TABLE_ROW_REGULATION)
        expect(self.page.locator(AwLocators.AW_TABLE_ROW_REGULATION)).to_contain_text("MT-CDPA")
        self.is_visible(AwLocators.AW_TABLE_ROW_RIGHT)
        expect(self.page.locator(AwLocators.AW_TABLE_ROW_RIGHT)).to_contain_text("Access")
        self.is_visible(AwLocators.AW_TABLE_ROW_BRAND)
        expect(self.page.locator(AwLocators.AW_TABLE_ROW_BRAND)).to_contain_text("Demo")
        self.is_visible(AwLocators.AW_TABLE_ROW_PERSONA)
        expect(self.page.locator(AwLocators.AW_TABLE_ROW_PERSONA)).to_contain_text("Customer")
        screenshot = self.page.screenshot()
        allure.attach(screenshot, name="Development_Asset_ID_Details", attachment_type=allure.attachment_type.PNG)
        self.is_visible(AwLocators.AW_INTEGRATION_ASSET_ID_OPTION)
        self.click(AwLocators.AW_INTEGRATION_ASSET_ID_OPTION)
        self.is_visible(AwLocators.AW_INTEGRATION_REGULATION_OPTION)
        self.click(AwLocators.AW_INTEGRATION_REGULATION_OPTION)
        self.is_visible(AwLocators.AW_INTEGRATION_SEARCH_REGULATION_INPUT)
        self.fill(AwLocators.AW_INTEGRATION_SEARCH_REGULATION_INPUT, "")
        self.fill(AwLocators.AW_INTEGRATION_SEARCH_REGULATION_INPUT, "MT-CDPA")
        expect(self.page.locator(AwLocators.AW_TABLE_ROW_ASSET_ID)).to_contain_text("5")
        self.is_visible(AwLocators.AW_TABLE_ROW_REGULATION)
        expect(self.page.locator(AwLocators.AW_TABLE_ROW_REGULATION)).to_contain_text("MT-CDPA")
        self.is_visible(AwLocators.AW_TABLE_ROW_RIGHT)
        expect(self.page.locator(AwLocators.AW_TABLE_ROW_RIGHT)).to_contain_text("Access")
        self.is_visible(AwLocators.AW_TABLE_ROW_BRAND)
        expect(self.page.locator(AwLocators.AW_TABLE_ROW_BRAND)).to_contain_text("Sam's Club")
        self.is_visible(AwLocators.AW_TABLE_ROW_PERSONA)
        expect(self.page.locator(AwLocators.AW_TABLE_ROW_PERSONA)).to_contain_text("Customer")
        screenshot = self.page.screenshot()
        allure.attach(screenshot, name="Development_Regulation_Details", attachment_type=allure.attachment_type.PNG)
        self.is_visible(AwLocators.AW_DEVELOPMENT_REGULATION_OPTION)
        self.click(AwLocators.AW_DEVELOPMENT_REGULATION_OPTION)
        self.is_visible(AwLocators.AW_INTEGRATION_BRAND_OPTION)
        self.click(AwLocators.AW_INTEGRATION_BRAND_OPTION)
        self.is_visible(AwLocators.AW_INTEGRATION_SEARCH_BRAND_INPUT)
        self.fill(AwLocators.AW_INTEGRATION_SEARCH_BRAND_INPUT, "")
        self.fill(AwLocators.AW_INTEGRATION_SEARCH_BRAND_INPUT, "Demo")
        expect(self.page.locator(AwLocators.AW_TABLE_ROW_ASSET_ID)).to_contain_text("7")
        self.is_visible(AwLocators.AW_TABLE_ROW_REGULATION)
        expect(self.page.locator(AwLocators.AW_TABLE_ROW_REGULATION)).to_contain_text("CA-CPRA")
        self.is_visible(AwLocators.AW_TABLE_ROW_RIGHT)
        expect(self.page.locator(AwLocators.AW_TABLE_ROW_RIGHT)).to_contain_text("Access")
        self.is_visible(AwLocators.AW_TABLE_ROW_BRAND)
        expect(self.page.locator(AwLocators.AW_TABLE_ROW_BRAND)).to_contain_text("Demo")
        self.is_visible(AwLocators.AW_TABLE_ROW_PERSONA)
        expect(self.page.locator(AwLocators.AW_TABLE_ROW_PERSONA)).to_contain_text("Visitor")
        screenshot = self.page.screenshot()
        allure.attach(screenshot, name="Development_Brand_Details", attachment_type=allure.attachment_type.PNG)

    def ready_to_go_live_feature(self):
        self.is_visible(AwLocators.AW_HOME_PAGE_READY_TO_GO_LIVE_BTN)
        self.click(AwLocators.AW_HOME_PAGE_READY_TO_GO_LIVE_BTN)
        #Select by asset ID
        self.is_visible(AwLocators.AW_INTEGRATION_SEARCH_ASSET_ID_INPUT)
        self.click(AwLocators.AW_INTEGRATION_SEARCH_ASSET_ID_INPUT)
        self.fill(AwLocators.AW_INTEGRATION_SEARCH_ASSET_ID_INPUT, "3072")
        expect(self.page.locator(AwLocators.AW_TABLE_ROW_ASSET_ID)).to_contain_text("3072")
        self.is_visible(AwLocators.AW_TABLE_ROW_REGULATION)
        expect(self.page.locator(AwLocators.AW_TABLE_ROW_REGULATION)).to_contain_text("CA-CPRA")
        self.is_visible(AwLocators.AW_TABLE_ROW_RIGHT)
        expect(self.page.locator(AwLocators.AW_TABLE_ROW_RIGHT)).to_contain_text("Access")
        self.is_visible(AwLocators.AW_TABLE_ROW_BRAND)
        expect(self.page.locator(AwLocators.AW_TABLE_ROW_BRAND)).to_contain_text("Walmart US")
        self.is_visible(AwLocators.AW_TABLE_ROW_PERSONA)
        expect(self.page.locator(AwLocators.AW_TABLE_ROW_PERSONA)).to_contain_text("Customer")
        screenshot = self.page.screenshot()
        allure.attach(screenshot, name="Ready_To_Go_Live_Asset_ID_Details", attachment_type=allure.attachment_type.PNG)
        self.is_visible(AwLocators.AW_INTEGRATION_ASSET_ID_OPTION)
        self.click(AwLocators.AW_INTEGRATION_ASSET_ID_OPTION)
        self.is_visible(AwLocators.AW_INTEGRATION_REGULATION_OPTION)
        self.click(AwLocators.AW_INTEGRATION_REGULATION_OPTION)
        self.is_visible(AwLocators.AW_INTEGRATION_SEARCH_REGULATION_INPUT)
        self.fill(AwLocators.AW_INTEGRATION_SEARCH_REGULATION_INPUT, "")
        self.fill(AwLocators.AW_INTEGRATION_SEARCH_REGULATION_INPUT, "CA-CPRA")
        expect(self.page.locator(AwLocators.AW_TABLE_ROW_ASSET_ID)).to_contain_text("33")
        self.is_visible(AwLocators.AW_TABLE_ROW_REGULATION)
        expect(self.page.locator(AwLocators.AW_TABLE_ROW_REGULATION)).to_contain_text("CA-CPRA")
        self.is_visible(AwLocators.AW_TABLE_ROW_RIGHT)
        expect(self.page.locator(AwLocators.AW_TABLE_ROW_RIGHT)).to_contain_text("Access")
        self.is_visible(AwLocators.AW_TABLE_ROW_BRAND)
        expect(self.page.locator(AwLocators.AW_TABLE_ROW_BRAND)).to_contain_text("Walmart US")
        self.is_visible(AwLocators.AW_TABLE_ROW_PERSONA)
        expect(self.page.locator(AwLocators.AW_TABLE_ROW_PERSONA)).to_contain_text("Customer")
        screenshot = self.page.screenshot()
        allure.attach(screenshot, name="Ready_To_Go_Live_Regulation_Details", attachment_type=allure.attachment_type.PNG)
        self.is_visible(AwLocators.AW_DEVELOPMENT_REGULATION_OPTION)
        self.click(AwLocators.AW_DEVELOPMENT_REGULATION_OPTION)
        self.is_visible(AwLocators.AW_INTEGRATION_BRAND_OPTION)
        self.click(AwLocators.AW_INTEGRATION_BRAND_OPTION)
        self.is_visible(AwLocators.AW_INTEGRATION_SEARCH_BRAND_INPUT)
        self.fill(AwLocators.AW_INTEGRATION_SEARCH_BRAND_INPUT, "")
        self.fill(AwLocators.AW_INTEGRATION_SEARCH_BRAND_INPUT, "Demo")
        expect(self.page.locator(AwLocators.AW_TABLE_ROW_ASSET_ID)).to_contain_text("6042")
        self.is_visible(AwLocators.AW_TABLE_ROW_REGULATION)
        expect(self.page.locator(AwLocators.AW_TABLE_ROW_REGULATION)).to_contain_text("OR-CPA")
        self.is_visible(AwLocators.AW_TABLE_ROW_RIGHT)
        expect(self.page.locator(AwLocators.AW_TABLE_ROW_RIGHT)).to_contain_text("Access")
        self.is_visible(AwLocators.AW_TABLE_ROW_BRAND)
        expect(self.page.locator(AwLocators.AW_TABLE_ROW_BRAND)).to_contain_text("Demo")
        self.is_visible(AwLocators.AW_TABLE_ROW_PERSONA)
        expect(self.page.locator(AwLocators.AW_TABLE_ROW_PERSONA)).to_contain_text("Customer")
        screenshot = self.page.screenshot()
        allure.attach(screenshot, name="Ready_To_Go_Live_Brand_Details", attachment_type=allure.attachment_type.PNG)

    def verify_snapshot_feature(self):
        self.is_visible(AwLocators.AW_SNAPSHOT_TAB_MSG)
        expect(self.page.locator(AwLocators.AW_SNAPSHOT_TAB_MSG)).to_contain_text("Snapshot of your Assets")
        self.is_visible(AwLocators.AW_SNAPSHOT_ALL_ASSETS_TAB)
        self.click(AwLocators.AW_SNAPSHOT_ALL_ASSETS_TAB)
        self.is_visible(AwLocators.AW_SNAPSHOT_ASSET_ID_BTN)
        self.is_visible(AwLocators.AW_SNAPSHOT_ASSET_NAME_BTN)
        self.is_visible(AwLocators.AW_SNAPSHOT_ASSET_OWNER_BTN)
        self.is_visible(AwLocators.AW_SNAPSHOT_PROGRAM_MGR_BTN)
        self.is_visible(AwLocators.AW_SNAPSHOT_APM_ID_BTN)
        screenshot = self.page.screenshot()
        allure.attach(screenshot, name="Snapshot_All_Assets", attachment_type=allure.attachment_type.PNG)
        self.is_visible(AwLocators.AW_SNAPSHOT_READY_TO_ENGAGE_TAB)
        self.click(AwLocators.AW_SNAPSHOT_READY_TO_ENGAGE_TAB)
        self.is_visible(AwLocators.AW_SNAPSHOT_ASSET_ID_BTN)
        self.is_visible(AwLocators.AW_SNAPSHOT_ASSET_NAME_BTN)
        self.is_visible(AwLocators.AW_SNAPSHOT_ASSET_OWNER_BTN)
        self.is_visible(AwLocators.AW_SNAPSHOT_PROGRAM_MGR_BTN)
        self.is_visible(AwLocators.AW_SNAPSHOT_APM_ID_BTN)
        screenshot = self.page.screenshot()
        allure.attach(screenshot, name="Snapshot_Ready_To_Engage_Assets", attachment_type=allure.attachment_type.PNG)
        self.is_visible(AwLocators.AW_SNAPSHOT_ENGAGED_TAB)
        self.click(AwLocators.AW_SNAPSHOT_ENGAGED_TAB)
        self.is_visible(AwLocators.AW_SNAPSHOT_ASSET_ID_BTN)
        self.is_visible(AwLocators.AW_SNAPSHOT_ASSET_NAME_BTN)
        self.is_visible(AwLocators.AW_SNAPSHOT_ASSET_OWNER_BTN)
        self.is_visible(AwLocators.AW_SNAPSHOT_PROGRAM_MGR_BTN)
        self.is_visible(AwLocators.AW_SNAPSHOT_APM_ID_BTN)
        screenshot = self.page.screenshot()
        allure.attach(screenshot, name="Snapshot_Engaged_Assets", attachment_type=allure.attachment_type.PNG)