from pages.base_page import BasePage
from locators.practice_test_table_locators import PracticeTestTableLocators
from playwright.sync_api import expect
import allure

class PracticeTestAutomationTestTablePage(BasePage):
    
    def open_browser(self, url):
        self.page.goto(url)
        self.click(PracticeTestTableLocators.TEST_TABLE_PAGE)
        expect(self.page).to_have_url("https://practicetestautomation.com/practice-test-table/")
        self.is_visible(PracticeTestTableLocators.TEST_TABLE_PAGE_HEADER)
        expect(self.page.locator(PracticeTestTableLocators.TEST_TABLE_PAGE_HEADER)).to_contain_text("Test Table")
        screenshot = self.page.screenshot()
        allure.attach(screenshot, name="Test_Table_Page_Header", attachment_type=allure.attachment_type.PNG)

    def use_filters(self):
        self.is_visible(PracticeTestTableLocators.TEST_TABLE_FILTER_TEXT)
        expect(self.page.locator(PracticeTestTableLocators.TEST_TABLE_FILTER_TEXT)).to_contain_text("Filters")
        self.is_visible(PracticeTestTableLocators.TEST_TABLE_JAVA_RADIO_BTN)
        expect(self.page.locator(PracticeTestTableLocators.TEST_TABLE_JAVA_RADIO_BTN)).to_be_enabled()
        self.click(PracticeTestTableLocators.TEST_TABLE_JAVA_RADIO_BTN)
        screenshot = self.page.screenshot()
        allure.attach(screenshot, name="Java_Radio_Btn", attachment_type=allure.attachment_type.PNG)
        self.is_visible(PracticeTestTableLocators.TEST_TABLE_PYTHON_RADIO_BTN)
        expect(self.page.locator(PracticeTestTableLocators.TEST_TABLE_PYTHON_RADIO_BTN)).to_be_enabled()
        self.click(PracticeTestTableLocators.TEST_TABLE_PYTHON_RADIO_BTN)
        screenshot = self.page.screenshot()
        allure.attach(screenshot, name="Python_Radio_Btn", attachment_type=allure.attachment_type.PNG)
        self.is_visible(PracticeTestTableLocators.TEST_TABLE_BEGINNER_CHECKBOX)
        self.click(PracticeTestTableLocators.TEST_TABLE_BEGINNER_CHECKBOX)
        self.is_visible(PracticeTestTableLocators.TEST_TABLE_INTERMEDIATE_CHECKBOX)
        self.click(PracticeTestTableLocators.TEST_TABLE_INTERMEDIATE_CHECKBOX)
        self.is_visible(PracticeTestTableLocators.TEST_TABLE_ADVANCED_CHECKBOX)
        self.click(PracticeTestTableLocators.TEST_TABLE_ADVANCED_CHECKBOX)
        self.is_visible(PracticeTestTableLocators.TEST_TABLE_NO_MATCHING_RECORDS_MSG)
        expect(self.page.locator(PracticeTestTableLocators.TEST_TABLE_NO_MATCHING_RECORDS_MSG)).to_contain_text("No matching courses.")
        screenshot = self.page.screenshot()
        allure.attach(screenshot, name="No_Matching_Records_Message", attachment_type=allure.attachment_type.PNG)
        self.is_visible(PracticeTestTableLocators.TEST_TABLE_ANY_RADIO_BTN)
        expect(self.page.locator(PracticeTestTableLocators.TEST_TABLE_ANY_RADIO_BTN)).to_be_enabled()
        self.click(PracticeTestTableLocators.TEST_TABLE_ANY_RADIO_BTN)
        self.is_visible(PracticeTestTableLocators.TEST_TABLE_BEGINNER_CHECKBOX)
        self.click(PracticeTestTableLocators.TEST_TABLE_BEGINNER_CHECKBOX)
        self.is_visible(PracticeTestTableLocators.TEST_TABLE_INTERMEDIATE_CHECKBOX)
        self.click(PracticeTestTableLocators.TEST_TABLE_INTERMEDIATE_CHECKBOX)
        self.is_visible(PracticeTestTableLocators.TEST_TABLE_ADVANCED_CHECKBOX)
        self.click(PracticeTestTableLocators.TEST_TABLE_ADVANCED_CHECKBOX)
        screenshot = self.page.screenshot()
        allure.attach(screenshot, name="Any_Radio_Btn_Selected", attachment_type=allure.attachment_type.PNG)
        self.is_visible(PracticeTestTableLocators.TEST_TABLE_SORT_BY_DROPDOWN_MENU)
        self.select_option(PracticeTestTableLocators.TEST_TABLE_SORT_BY_DROPDOWN_MENU, value="col_id")
        self.is_visible(PracticeTestTableLocators.TEST_TABLE_CHECK)
        self.is_visible(PracticeTestTableLocators.TEST_TABLE_COLUMN_ID)
        self.is_visible(PracticeTestTableLocators.TEST_TABLE_COLUMN_COURSE_NAME)
        self.is_visible(PracticeTestTableLocators.TEST_TABLE_COLUMN_LANGUAGE)
        self.is_visible(PracticeTestTableLocators.TEST_TABLE_COLUMN_LEVEL)
        self.is_visible(PracticeTestTableLocators.TEST_TABLE_COLUMN_ENROLLMENTS)
        self.is_visible(PracticeTestTableLocators.TEST_TABLE_COLUMN_LINK)
        self.is_visible(PracticeTestTableLocators.TEST_TABLE_FIRST_ROW)
        self.select_option(PracticeTestTableLocators.TEST_TABLE_SORT_BY_DROPDOWN_MENU, label="Course Name")
        self.is_visible(PracticeTestTableLocators.TEST_TABLE_CHECK)
        self.is_visible(PracticeTestTableLocators.TEST_TABLE_COLUMN_ID)
        self.is_visible(PracticeTestTableLocators.TEST_TABLE_COLUMN_COURSE_NAME)
        self.is_visible(PracticeTestTableLocators.TEST_TABLE_COLUMN_LANGUAGE)
        self.is_visible(PracticeTestTableLocators.TEST_TABLE_COLUMN_LEVEL)
        self.is_visible(PracticeTestTableLocators.TEST_TABLE_COLUMN_ENROLLMENTS)
        self.is_visible(PracticeTestTableLocators.TEST_TABLE_COLUMN_LINK)
        self.is_visible(PracticeTestTableLocators.TEST_TABLE_FIRST_ROW)
        self.select_option(PracticeTestTableLocators.TEST_TABLE_SORT_BY_DROPDOWN_MENU, index=2)
        self.is_visible(PracticeTestTableLocators.TEST_TABLE_CHECK)
        self.is_visible(PracticeTestTableLocators.TEST_TABLE_COLUMN_ID)
        self.is_visible(PracticeTestTableLocators.TEST_TABLE_COLUMN_COURSE_NAME)
        self.is_visible(PracticeTestTableLocators.TEST_TABLE_COLUMN_LANGUAGE)
        self.is_visible(PracticeTestTableLocators.TEST_TABLE_COLUMN_LEVEL)
        self.is_visible(PracticeTestTableLocators.TEST_TABLE_COLUMN_ENROLLMENTS)
        self.is_visible(PracticeTestTableLocators.TEST_TABLE_COLUMN_LINK)
        self.is_visible(PracticeTestTableLocators.TEST_TABLE_FIRST_ROW)
        screenshot = self.page.screenshot()
        allure.attach(screenshot, name="Table_records", attachment_type=allure.attachment_type.PNG)
