[pytest]
pythonpath = .
testpaths = tests
addopts = --clean-alluredir
markers = 
    smoke: Smoke tests - critical path only
    functional: Functional tests - Feature coverage
    regression: Full regression suite
    api: API tests - Testing API endpoints