class AwLocators:
    USERNAME_INPUT = "#username1"
    PASSWORD_INPUT = "#password"
    SIGN_IN_BUTTON = "xpath=//*[@title='Sign In']"
    DCSP_HOME_PAGE_TENANT_DROPDOWN = "xpath=//*[@data-testid='dropdown-element']"
    US_TENANT_OPTION = "xpath=//*[contains(text(),'US')]"
    AW_LAUNCH_BTN = "xpath=(//*[contains(text(),'Launch')])[5]"
    AW_INVALID_CREDENTIALS_MSG = "xpath=//div[@class='ping-error']"
    AW_HOME_PAGE_DEVELOPMENT_BTN = "xpath=(//*[contains(text(),'Development')])[2]"
    AW_HOME_PAGE_CONTINUE_DEVELOPMENT_BTN = "xpath=//*[contains(text(),'Continue Development')]"
    AW_HOME_PAGE_REVIEW_AND_APPROVE_BTN = "xpath=//*[contains(text(),'Review and approve')]"
    AW_HOME_PAGE_REVIEW_AND_APPROVE_EXCEPTION_MSG = "xpath=//h1[contains(text(),'Exception in remote application')]"
    AW_HOME_PAGE_INTEGRATION_BTN = "xpath=//*[contains(text(),'Integration')]"
    AW_INTEGRATION_FEATURE_DESCRIPTION = "xpath=//*[contains(text(),'List of data mapping entries that needs to be integrated with DC core platform.')]"
    AW_INTEGRATION_NO_RESULTS_MSG = "xpath=//div[contains(text(),'No results found!')]"
    AW_INTEGRATION_KAFKA_TAB = "xpath=//div[contains(text(),'Kafka')]"
    AW_INTEGRATION_PULL_TAB = "xpath=//div[contains(text(),'Pull')]"
    AW_INTEGRATION_MANUAL_TAB = "xpath=//div[contains(text(),'Manual')]"
    AW_INTEGRATION_ASSET_ID_OPTION = "xpath=//span[contains(text(),'Asset ID')]"
    AW_INTEGRATION_REGULATION_OPTION = "xpath=//span[contains(text(),'Regulation')]"
    AW_DEVELOPMENT_REGULATION_OPTION = "xpath=(//span[contains(text(),'Regulation')])[1]"
    AW_INTEGRATION_BRAND_OPTION = "xpath=//span[contains(text(),'Brand')]"
    AW_DEVELOPMENT_BRAND_OPTION = "xpath=(//span[contains(text(),'Brand')])[1]"
    AW_INTEGRATION_PERSONA_OPTION = "xpath=//span[contains(text(),'Persona')]"
    AW_TABLE_ROW_ASSET_ID = "xpath=(//table[contains(@class,'aw-fixed-table-header')]//tbody//tr[contains(@class,'ld_JP')]/td[1])[1]"
    AW_TABLE_ROW_REGULATION = "xpath=(//table[contains(@class,'aw-fixed-table-header')]//tbody//tr[contains(@class,'ld_JP')]/td[2])[1]"
    AW_TABLE_ROW_RIGHT = "xpath=(//table[contains(@class,'aw-fixed-table-header')]//tbody//tr[contains(@class,'ld_JP')]/td[3])[1]"
    AW_TABLE_ROW_BRAND = "xpath=(//table[contains(@class,'aw-fixed-table-header')]//tbody//tr[contains(@class,'ld_JP')]/td[4])[1]"
    AW_TABLE_ROW_PERSONA = "xpath=(//table[contains(@class,'aw-fixed-table-header')]//tbody//tr[contains(@class,'ld_JP')]/td[5])[1]"
    AW_INTEGRATION_CLOSE_BTN = "xpath=//button[@aria-label='Close Panel']"
    AW_INTEGRATION_SEARCH_ASSET_ID_INPUT = "xpath=//input[@placeholder='Search by Asset ID']"
    AW_INTEGRATION_SEARCH_REGULATION_INPUT = "xpath=//input[@placeholder='Search by Regulation']"
    AW_INTEGRATION_SEARCH_BRAND_INPUT = "xpath=//input[@placeholder='Search by Brand']"
    AW_INTEGRATION_SEARCH_PERSONA_INPUT = "xpath=//input[@placeholder='Search by Brand']"
    AW_HOME_PAGE_DEVELOPMENT_BTN = "xpath=(//*[contains(text(),'Development')])[2]"
    AW_HOME_PAGE_READY_TO_GO_LIVE_BTN = "xpath=//*[contains(text(),'Ready to go live')]"
    AW_HOME_PAGE_CONTINUE_DEVELOPMENT_FETCH_ASSET_TASK_HEADER = "xpath=(//*[contains(text(),'Fetch the Asset task')])[2]"
    AW_CONTINUE_DEVELOPMENT_FIRST_NAME_INPUT = "xpath=//input[@placeholder='First name']"
    AW_CONTINUE_DEVELOPMENT_LAST_NAME_INPUT = "xpath=//input[@placeholder='Last name']"
    AW_CONTINUE_DEVELOPMENT_EMAIL_INPUT = "xpath=//input[@placeholder='Email address']"
    AW_CONTINUE_DEVELOPMENT_CREATE_REQ_BTN = "xpath=//button[contains(., 'Create test request')]"
    AW_SNAPSHOT_TAB_MSG = "xpath=//span[contains(text(),'Snapshot of your Assets')]"
    AW_SNAPSHOT_ALL_ASSETS_TAB = "xpath=//span[contains(text(),'All assets')]"
    AW_SNAPSHOT_READY_TO_ENGAGE_TAB = "xpath=//span[contains(text(),'Ready to engage')]"
    AW_SNAPSHOT_ENGAGED_TAB = "xpath=//span[contains(text(),'Engaged')]"
    AW_SNAPSHOT_ASSET_ID_BTN = "xpath=//div[contains(text(),'Asset ID ')]"
    AW_SNAPSHOT_ASSET_NAME_BTN = "xpath=//div[contains(text(),'Asset Name ')]"
    AW_SNAPSHOT_ASSET_OWNER_BTN = "xpath=//div[contains(text(),'Asset Owner ')]"
    AW_SNAPSHOT_PROGRAM_MGR_BTN = "xpath=//div[contains(text(),'Program Manager ')]"
    AW_SNAPSHOT_APM_ID_BTN = "//div[contains(text(),'APM ID ')]"

    
    
