class PracticeTestExceptionLocators:
    EXCEPTION_PAGE = "//a[contains(text(),'Test Exceptions')]"
    EXCEPTION_PAGE_HEADER = "xpath=//h2[contains(text(),'Test Exceptions')]"
    ROW_ONE_TEXT = "xpath=//div/label[contains(text(),'Row 1')]"
    ROW_ONE_EDIT_BUTTON = "xpath=(//div/button[contains(text(),'Edit')])[1]"
    ROW_ONE_INPUT_FIELD = "xpath=(//div/input[@class='input-field'])[1]"
    ROW_ONE_SAVE_BUTTON = "xpath=(//div/button[contains(text(),'Save')])[1]"
    ROW_ONE_SAVE_SUCCESS_MSG = "xpath=//div[contains(text(),'Row 1 was saved')]"
    ROW_ONE_ADD_BUTTON = "xpath=(//div/button[contains(text(),'Add')])[1]"
    ROW_TWO_ADD_MSG = "xpath=//div[contains(text(),'Row 2 was added')]"
    ROW_TWO_INPUT_FIELD = "xpath=(//div/input[@class='input-field'])[2]"
    ROW_TWO_SAVE_BUTTON = "xpath=(//div/button[contains(text(),'Save')])[2]"
    ROW_TWO_SAVE_SUCCESS_MSG = "xpath=//div[contains(text(),'Row 2 was saved')]"
    ROW_TWO_REMOVE_BUTTON = "xpath=(//div/button[contains(text(),'Remove')])[1]"
    ROW_TWO_REMOVE_MSG = "xpath=//div[contains(text(),'Row 2 was removed')]"